extends: relaxed

rules:
  line-length:
    max: 200
    allow-non-breakable-words: true
  trailing-spaces: enable
  indentation:
    spaces: 2
    indent-sequences: consistent
  truthy:
    allowed-values: ['true', 'false', 'on', 'off']
    check-keys: false
