apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-prod

resources:
  - ../../base
  - rollout.yaml
  - analysis-template.yaml
  - hpa.yaml

# In prod we delete the base Deployment and let the Rollout own the pods.
# Argo Rollouts produces a ReplicaSet with the same selector.
patches:
  - patch: |-
      $patch: delete
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: demo-api

images:
  - name: ghcr.io/mohammedabood/demo-api
    newTag: "0.1.0"

commonLabels:
  environment: prod
